config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # get 'reviews/post'
  # get 'restaurants/get'
  # get 'restaurants/new'
  # get 'restaurants/post'
  # get 'restaurants/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5), message: "%{value} is not a valid rating" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def create
  end

  def new
    @restaurant = Restaurant.new
  end

  def post

  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def post

  end

  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurant.each do |resto| %>

  <li>
   <%= link_to(resto.name, restaurant_path(resto)) %>
  </li>

  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

app/views/restaurants/post.html.erb
<h1>Restaurants#post</h1>
<p>Find me in app/views/restaurants/post.html.erb</p>

app/views/restaurants/show.html.erb
<h1>Restaurant</h1>
<p>
  <strong>Name : </strong>
<%= @restaurant.name %>
</p>

<p>
  <strong>Address : </strong>
<%= @restaurant.address %>
</p>


 <h2>Reviews : </h2>
<%= @restaurant.reviews.each do |review| %>

<p> <%= review.content %> </p>
<%= link_to "delete review", review_path(review) %>
<% end  %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/post.html.erb
<h1>Reviews#post</h1>
<p>Find me in app/views/reviews/post.html.erb</p>